version: '3.8'

services:
  go-service:
    build:
      context: ./service
    container_name: system-service
    ports:
      - "8080:8080"
    networks:
      - netstorxcelerator-network
  
  ethernet-driver:
    build:
      context: ./drivers/ethernet
    container_name: ethernet-driver
    networks:
      - netstorxcelerator-network

  packet-app:
    build:
      context: ./apps/packxclerator
    container_name: packet-app
    depends_on:
      - ethernet-driver
    networks:
      - netstorxcelerator-network

networks:
  netstorxcelerator-network:
    driver: bridge