+-----------------------+
|    Containerized      |
|  System Services (Go) |
+-----------------------+
           |
           v
+-----------------------+
|      Docker Engine    |
|  (Containerization)   |
+-----------------------+
           |
           v
+-----------------------+           +-----------------------+
|     Rust-based        |<--------->|       DPDK/VPP        |
|  Ethernet Drivers     |           | Packet Acceleration   |
+-----------------------+           +-----------------------+
           |
           v
+-----------------------+
|  Linux Kernel/OS      |
+-----------------------+